apiVersion: v1
kind: Service
metadata:
  name: dcvpg-api
  labels:
    app: dcvpg-api
spec:
  selector:
    app: dcvpg-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dcvpg-dashboard
  labels:
    app: dcvpg-dashboard
spec:
  selector:
    app: dcvpg-dashboard
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
